In [1]:
import numpy as np
import math
import scipy.integrate as integrate
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
l = 0.02
epsilon = l/2/math.pi

In [15]:
kk = np.arange(-5,5)

In [17]:
kk[:5]

array([-5, -4, -3, -2, -1])

In [18]:
kk[5:]

array([0, 1, 2, 3, 4])

In [22]:
def A_operator(kx,ky,n):
    
    #n = 40
    a = 1.5
    b = 1.4
    c = 1
    d = 0.6
    NN = (2*n+1)*(2*n+1)
    A = np.zeros((2*NN, 2*NN))
    epsilon = l/2/math.pi
    
    for j in range(-n,n+1):
        for i in range(-n,n+1):
            index = (j+n)*(2*n+1)+i+n
            sigmaxxx = np.zeros((1,2*NN))
            sigmaxyy = np.zeros((1,2*NN))
            sigmayxx = np.zeros((1,2*NN))
            sigmayyy = np.zeros((1,2*NN))
        
            sigmaxxx[0,index] = (a+2*c)*(i/epsilon + kx)*(i/epsilon + kx)
            sigmaxxx[0,index+NN] =a*(j/epsilon + ky)*(i/epsilon + kx)
            sigmaxyy[0,index] = c*(j/epsilon + ky)*(j/epsilon + ky)
            sigmaxyy[0,index+NN] = c*(i/epsilon + kx)*(j/epsilon + ky)
            sigmayxx[0,index] = c*(j/epsilon + ky)*(i/epsilon + kx)
            sigmayxx[0,index+NN] = c*(i/epsilon + kx)*(i/epsilon + kx)
            sigmayyy[0,index] = a*(i/epsilon + kx)*(j/epsilon + ky)
            sigmayyy[0,index+NN] = (a+2*c)*(j/epsilon + ky)*(j/epsilon + ky)
            
            
            
            if i!=-n:
                sigmaxxx[0,index-1] = b/2*(i/epsilon + kx)*(i/epsilon - 1/epsilon + kx)
                sigmayyy[0,index-1] = b/2*(i/epsilon + kx)*(j/epsilon + ky)
                sigmaxxx[0,index+NN-1] =b/2*(j/epsilon + ky)*(i/epsilon - 1/epsilon + kx)
                sigmayyy[0,index+NN-1] = b/2*(j/epsilon + ky)*(j/epsilon + ky)



            if i!=n:
                sigmaxxx[0,index+1] = b/2*(i/epsilon + kx)*(i/epsilon + 1/epsilon + kx)
                sigmayyy[0,index+1] = b/2*(i/epsilon + kx)*(j/epsilon + ky)
                sigmaxxx[0,index+NN+1] =b/2*(j/epsilon + ky)*(i/epsilon + 1/epsilon + kx)
                sigmayyy[0,index+NN+1] = b/2*(j/epsilon + ky)*(j/epsilon + ky)

            if j!=-n:
                sigmaxxx[0,index-2*n-1] = d*(i/epsilon + kx)*(i/epsilon + kx)
                sigmaxyy[0,index-2*n-1] = d/2*(j/epsilon + ky)*(j/epsilon -1/epsilon + ky)
                sigmaxyy[0,index+NN-2*n-1] = d/2*(i/epsilon + kx)*(j/epsilon - 1/epsilon + ky)
                sigmayxx[0,index-2*n-1] = d/2*(j/epsilon + ky)*(i/epsilon + kx)
                sigmayxx[0,index+NN-2*n-1] = d/2*(i/epsilon + kx)*(i/epsilon + kx)
                sigmayyy[0,index+NN-2*n-1] = d*(j/epsilon + ky)*(j/epsilon - 1/epsilon + ky)



            if j!=n:
                sigmaxxx[0,index+2*n+1] = d*(i/epsilon + kx)*(i/epsilon + kx)
                sigmaxyy[0,index+2*n+1] = d/2*(j/epsilon + ky)*(j/epsilon + 1/epsilon + ky)
                sigmaxyy[0,index+NN+2*n+1] = d/2*(i/epsilon + kx)*(j/epsilon + 1/epsilon + ky)
                sigmayxx[0,index+2*n+1] = d/2*(j/epsilon + ky)*(i/epsilon + kx)
                sigmayxx[0,index+NN+2*n+1] = d/2*(i/epsilon + kx)*(i/epsilon + kx)
                sigmayyy[0,index+NN+2*n+1] = d*(j/epsilon + ky)*(j/epsilon + 1/epsilon + ky)
            
            A[index,:] = sigmaxxx + sigmaxyy
            A[index+NN,:] = sigmayxx + sigmayyy
        
    
    return A

In [25]:
eigen = np.linalg.eig(A_operator(0.2,0.2,5))
eigen[0]

array([2.07956279e+07, 2.08012130e+07, 2.08012974e+07, 2.08068825e+07,
       1.60533233e+07, 1.60630400e+07, 1.60583624e+07, 1.60579988e+07,
       1.52675042e+07, 1.52788517e+07, 1.52739605e+07, 1.52723860e+07,
       1.26567636e+07, 1.26695514e+07, 1.30283480e+07, 1.30137139e+07,
       1.29651251e+07, 1.29088073e+07, 1.28981284e+07, 1.28448777e+07,
       1.13742663e+07, 1.14096515e+07, 1.15281739e+07, 1.15008243e+07,
       1.09108041e+07, 1.08404096e+07, 1.08299528e+07, 1.07531535e+07,
       1.05831653e+07, 1.06015475e+07, 1.02823961e+07, 1.02872695e+07,
       9.51783670e+06, 9.52247061e+06, 9.15954922e+06, 9.16469406e+06,
       8.78147466e+06, 8.77258510e+06, 8.74879921e+06, 8.75621970e+06,
       8.30363077e+06, 8.30772798e+06, 7.97469341e+06, 7.93820046e+06,
       7.91679948e+06, 7.88894452e+06, 7.81727194e+06, 7.82975421e+06,
       7.14504043e+06, 7.14009440e+06, 7.11885828e+06, 7.12251155e+06,
       7.03997278e+06, 7.04365658e+06, 6.75247636e+06, 6.68423749e+06,
      

In [24]:
eigen = np.linalg.eig(A_operator(0.2,1.2,5))
np.min(eigen[0])

-1.0190857113310923

In [12]:
def Eigenfunc(x,y,coeff,n):
    
    this_m = np.arange(-n,n+1)
    this_n = np.arange(-n,n+1)
    
    exp_mx = np.exp(1j*this_m*x/epsilon)
    exp_ny = np.exp(1j*this_n*y/epsilon)
    
    exp_xy_mat = np.outer(exp_ny,exp_mx)
    exp_xy_vec = exp_xy_mat.flatten()
    
    return np.dot(exp_xy_vec,coeff)

In [33]:
def myfunctoint_cal(kx,ky,x,y,this_x,this_y):
    n= 5
    NN = (2*n+1)*(2*n+1)
    #this_x = l/8
    eigen = np.linalg.eig(A_operator(kx,ky,n))
    coeff = eigen[1][:,np.argmin(eigen[0])]
    coeff_x = coeff[:NN]
    coeff_y = coeff[NN:]
    lamda_cal = np.min(eigen[0])
    
    fi_x = Eigenfunc(this_x,this_y,coeff_x,n)
    fi_y = Eigenfunc(this_x,this_y,coeff_y,n)
    
    fi_xp = Eigenfunc(this_x+x,this_y+y,coeff_x,n)
    fi_yp = Eigenfunc(this_x+x,this_y+y,coeff_y,n)
    
    kernel_toint = np.zeros((2, 2),dtype=complex)
    
    kernel_toint[0,0] = fi_x*np.conj(fi_xp)
    kernel_toint[0,1] = fi_x*np.conj(fi_yp)
    kernel_toint[1,0] = fi_y*np.conj(fi_xp)
    kernel_toint[1,1] = fi_y*np.conj(fi_yp)
    

    return (np.exp(-1j*x*kx-1j*y*ky)*kernel_toint).real*lamda_cal/l
    #return (np.exp(-1j*x*kx-1j*y*ky)*fi_x*np.conj(fi_xp)).real*lamda_cal/l

In [38]:
def myfunctoint_cal_testxx(kx,ky,x,y,this_x,this_y):
    return myfunctoint_cal(kx,ky,x,y,this_x,this_y)[0,0]

In [41]:
def myfunc_cal(x,y,this_x,this_y):
    return integrate.nquad(myfunctoint_cal_testxx,[[-1/2/epsilon,1/2/epsilon],[-1/2/epsilon,1/2/epsilon]],args=(x,y,this_x,this_y))[0]

In [42]:
number = 100
kernel_test = np.zeros((100,100))
xx = np.linspace(-0.2,0.2,num = number)
yy = np.linspace(-0.2,0.2,num = number)
for i in range(number):
    print(i)
    for j in range(number):
        kernel[i,j] = myfunc_cal(xx[i],yy[j],0,0)

0


KeyboardInterrupt: 